buildscript {
    ext.kotlin_version = '2.0.20'
    ext.realm_version = '2.3.0'
    ext.nav_version = "2.8.5"

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
        classpath 'com.android.tools.build:gradle:8.13.0'

        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.9'

        classpath 'com.google.gms:google-services:4.4.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
    id 'io.realm.kotlin' version "$realm_version" apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
    delete rootProject.projectDir.absolutePath + "/mobile/release"
    delete rootProject.projectDir.absolutePath + "/wear/release"
}
