name: Continuous Integration

env:
  BUILD_NUMBER: ${{ github.run_number }}

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches-ignore:
      - 'copilot/**'

concurrency:
  group: build-android-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Checkout PR
      uses: actions/checkout@v4

    - name: 🤖 Android setup
      uses: ./.github/actions/android-setup
      with:
        secrets-properties-b64: ''
        google-services-json-b64: ${{ secrets.GOOGLE_SERVICES_JSON_64 }}

    - name: 👷‍♀️ Build with Gradle
      run: ./gradlew build

    - name: 🛜 Upload reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Lint Results
        path: mobile/build/reports/lint-results-debug.html


  check-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Checkout PR
      uses: actions/checkout@v4

    - name: 🌯 Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v3

  deploy-app:
    runs-on: ubuntu-latest
    environment: Google Play Store Deployment
    needs: [build, check-gradle-wrapper]
    if: ${{ github.event_name == 'push' && github.ref_name == 'production' }}

    steps:
    - name: 🚚 Checkout PR
      uses: actions/checkout@v4

    - name: 🤖 Android setup
      uses: ./.github/actions/android-setup
      with:
        secrets-properties-b64: ${{ secrets.SECRETS_PROPERTIES_64 }}
        google-services-json-b64: ${{ secrets.GOOGLE_SERVICES_JSON_64 }}

    - name: 📑 Create keystore file
      env:
        KEYSTORE_64: ${{ secrets.KEYSTORE_64 }}
      run: echo $KEYSTORE_64 | base64 -di > ./keys/release-keystore.jks

    - name: 👷‍♀️ Bundle Release
      id: bundleRelease
      env:
        STORE_PASS: ${{ secrets.STORE_PASS }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASS: ${{ secrets.KEY_PASS }}
      run: ./gradlew :mobile:bundleRelease :wear:bundleRelease

    - name: 🛜 Upload Android Release to Play Store
      uses: r0adkll/upload-google-play@v1.1.3
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.shelbeely.opentransition
        releaseFiles: ${{ vars.RELEASE_BUNDLE_PATH }}
        track: alpha
        mappingFile: ${{ vars.RELEASE_MAPPING_PATH }}

    - name: ⌚ Upload Wear Release to Play Store
      uses: r0adkll/upload-google-play@v1.1.3
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.shelbeely.opentransition.wear
        releaseFiles: wear/build/outputs/bundle/release/wear-release.aab
        track: alpha

    - name: 🔖 Tag release
      env:
        TAG_NAME: 'v${{ steps.bundleRelease.outputs.VERSION_NAME }}'
      run: |
        git config --global user.name "Continuous Integration"
        git config --global user.email "username@users.noreply.github.com"
        git tag "$TAG_NAME"
        git push origin "$TAG_NAME"
