/*
 * Copyright © 2018 TransTracks. All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.shelbeely.opentransition.ui.voicesession

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Card
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FilterChip
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import com.shelbeely.opentransition.R
import com.shelbeely.opentransition.database.room.entities.AudioAnalysisEntity
import com.shelbeely.opentransition.database.room.entities.VoiceGoalEntity
import com.shelbeely.opentransition.ui.widget.SpectrogramView
import com.shelbeely.opentransition.util.VoiceMetric
import java.io.File
import java.util.Locale
import kotlin.math.roundToInt

/**
 * Full-page detail view for a single voice recording session.
 *
 * Shows:
 * - Full-width [SpectrogramView] with pitch curve overlay and optional playback cursor
 * - Plain measurement row: duration, voiced %, intensity, pitch range
 * - Session summary text generated by [com.shelbeely.opentransition.util.SessionSummaryBuilder]
 * - "Your goals" row listing which user-defined goals this session hit
 *
 * All values are displayed as plain measurements — no colour coding, no icons,
 * no implied "correct" direction.
 *
 * @param analysis       The [AudioAnalysisEntity] for this session.
 * @param audioFilePath  Absolute path to the audio file (for the spectrogram).
 * @param playbackProgress Playback cursor position 0–1 (driven by AudioPlayerManager).
 * @param goalHits       Goals whose target range was met by this session.
 * @param onBack         Navigate up.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun VoiceSessionDetailScreen(
    analysis: AudioAnalysisEntity,
    audioFilePath: String,
    playbackProgress: Float = 0f,
    goalHits: List<VoiceGoalEntity> = emptyList(),
    onBack: () -> Unit
) {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.voice_session_detail_title)) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = stringResource(R.string.back)
                        )
                    }
                }
            )
        }
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 16.dp)
        ) {
            // ── Spectrogram with pitch curve overlay ──────────────────────
            AndroidView(
                factory = { ctx ->
                    SpectrogramView(ctx).also { sv ->
                        val file = File(audioFilePath)
                        if (file.exists()) sv.setAudioFile(file)
                    }
                },
                update = { sv -> sv.setPlaybackProgress(playbackProgress) },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(180.dp)
            )

            Spacer(modifier = Modifier.height(16.dp))

            // ── Plain measurement row ─────────────────────────────────────
            Text(
                text = stringResource(R.string.voice_session_metrics_title),
                style = MaterialTheme.typography.titleMedium
            )
            Spacer(modifier = Modifier.height(8.dp))
            MetricsRow(analysis = analysis)

            Spacer(modifier = Modifier.height(16.dp))
            HorizontalDivider()
            Spacer(modifier = Modifier.height(16.dp))

            // ── Session summary ───────────────────────────────────────────
            if (analysis.sessionSummaryText.isNotBlank()) {
                Text(
                    text = stringResource(R.string.voice_session_summary_title),
                    style = MaterialTheme.typography.titleMedium
                )
                Spacer(modifier = Modifier.height(8.dp))
                Card(modifier = Modifier.fillMaxWidth()) {
                    Text(
                        text = analysis.sessionSummaryText,
                        style = MaterialTheme.typography.bodyMedium,
                        modifier = Modifier.padding(16.dp)
                    )
                }
                Spacer(modifier = Modifier.height(16.dp))
                HorizontalDivider()
                Spacer(modifier = Modifier.height(16.dp))
            }

            // ── Goal hits ─────────────────────────────────────────────────
            if (goalHits.isNotEmpty()) {
                Text(
                    text = stringResource(R.string.voice_session_goals_title),
                    style = MaterialTheme.typography.titleMedium
                )
                Spacer(modifier = Modifier.height(8.dp))
                goalHits.forEach { goal ->
                    FilterChip(
                        selected = true,
                        onClick = {},
                        label = { Text(goal.name) },
                        modifier = Modifier.padding(end = 8.dp, bottom = 4.dp)
                    )
                }
                Spacer(modifier = Modifier.height(16.dp))
            }
        }
    }
}

@Composable
private fun MetricsRow(analysis: AudioAnalysisEntity) {
    val metrics = listOf(
        stringResource(R.string.metric_duration) to
            "${String.format(Locale.US, "%.1f", analysis.durationSeconds)} s",
        stringResource(R.string.metric_voiced_pct) to
            "${(analysis.voicedRatio * 100f).roundToInt()}%",
        stringResource(R.string.metric_intensity) to
            "${String.format(Locale.US, "%.1f", analysis.intensityMeanDb)} dBFS",
        stringResource(R.string.metric_pitch_range) to
            "${analysis.pitchRangeHz.roundToInt()} Hz",
        stringResource(R.string.metric_pitch_avg) to
            "${analysis.f0Mean.roundToInt()} Hz"
    )
    Column {
        metrics.forEach { (label, value) ->
            Row(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = 4.dp),
                horizontalArrangement = Arrangement.SpaceBetween
            ) {
                Text(text = label, style = MaterialTheme.typography.bodyMedium)
                Text(
                    text = value,
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.75f)
                )
            }
        }
    }
}
